# Generated by Django 4.2 on 2023-04-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalModules',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('module_number', models.IntegerField()),
                ('module_name', models.TextField()),
                ('module_description', models.TextField()),
            ],
            options={
                'db_table': 'educational_modules'
            },
        ),
    ]
